language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travice Ci 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - jb.park.kr@gmail.com